import Head from 'next/head';
import { GetServerSidePropsContext } from 'next';
import { authenticateRoute } from '../utils/authenticateRoute.ts';

//default home page

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>hello</h1>
    </>
  );
}

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const response = await authenticateRoute(ctx);

  if (response.redirect) {
    return {
      redirect: response.redirect,
    };
  }

  return {
    props: response.props,
  };
}
